### ISSUE TITLE
Simple hints for libXC requirements

### ISSUE THREAD

**Issue by bhourahine** [dftbplus/skprogs#56]
**What is your suggested feature? Please describe.**
More documentation for local compilation (particularly libXC)

**Is your feature request related to a problem? Please describe.**
Would be good to spell out:
* don't use debian libXC packages
* If using the libXM configure script, set a local install path (as the skprogs cmake needs it to be installed for the package files to work)

**Describe the solution you'd like**
Slight expansion of the README

**Comment by vanderhe** [comment]
Providing SkProgs via conda-forge would be a significant improvement in user-experience. Since [libXC >=v6.0.0](https://github.com/conda-forge/libxc-feedstock) is packaged for quite some time now, there is nothing that prevents us from doing so as well, except maybe this weird segfault that we experience when building as a shared library. @aradi and I have been trying to debug, no success. Maybe you can spot anything we are missing. My hope was that the segfault solves itself as soon as conda-forge's toolchain moves on, but that does not seem to be the case...

**Comment by vanderhe** [comment]
Quick update: conda-forge issues resolved (see https://github.com/conda-forge/skprogs-feedstock/pull/1), we could now release version 0.2 and distribute SkProgs (Python components in separate feedstock).

**Comment by vanderhe** [comment]
@bhourahine I opened a draft PR #64. Could you have a look at it and add missing information? We block all libXC versions <6.0.0, therefore Debian/Ubuntu packages should at least not pass the configuration step. Do you want to add some useful comments covering this?

**Comment by vanderhe** [comment]
Personal reminder: Add remark covering `YOUR_SKPROGS_INSTALL_FOLDER`.
