### ISSUE TITLE
An update of `skdef` dictionary does not update `OnecenterParameters` and `TwocenterParameters` fields

### ISSUE THREAD

**Issue by samtsevich** [dftbplus/skprogs#67]
**Describe the bug**

The problem appears when I manually set the path to the config file. 
This means `skprogs` first reads the default `skdef.hsd` file and then reads another, let's say, `my_skdef.hsd` file. 
The next step is an update of `Skdef` dictionary by another dictionary made from `my_skdef.hsd`.
However, during this update, only the `atomparamters` field is updating, but not `OnecenterParameters` and not `TwocenterParameters`.

All of the written above can be easily fixed below [this line](https://github.com/dftbplus/skprogs/blob/3349344ff331de964c460e00081e6676b5650954/sktools/src/sktools/skdef.py#L70)

If that was made on purpose, please, let me know why that was made in a such way.

**Comment by vanderhe** [comment]
Hi @samtsevich Artem,

you are right, the fact that `./skdef.hsd` is always parsed is counterintuitive. Additionally, as you correctly pointed out, the update mechanism in the backend is broken and has probably never been finalized due to difficulties in the implementation process. I created PR #70 that lifts the restriction of requiring `./skdef.hsd` to be present regardless of the user input and further disables the feature of reading in multiple configuration files, at least as long as the backend has not caught up.

The motivation of having the freedom to parse multiple config files in the first place is rooted in the possible parametrization task of extending an existing set like mio-1-1 by e.g. titanium as for the tiorg mio-extension. In that case it could be handy to provide mio-related information in a separate file that is left untouched in the parametrization process.

Best regards
Tammo
