### ISSUE TITLE
Exponents?

### ISSUE THREAD

**Issue by andrewshyichuk** [dftbplus/skprogs#99]
**What is your suggested feature? Please describe.**

I wonder where do I get exponents for atoms that are not in the examples. 
Their physical sense is not specified. I assume those are zetas for the STOs, as described in:
https://en.wikipedia.org/wiki/Slater-type_orbital

If that is true - I guess I can use any basis I like and fit STOs to it?

Or, are those exponents for GTOs that approximate STOs? If so, can I use exponents from whichever basis I like, as long as it is good enough to resemble an STO? Would ANO-RCC work?

**Comment by vanderhe** [comment]
Hi @andrewshyichuk,

we usually resort to even-tempered STOs, by generating the exponents according to a geometric series. If you have installed the `sktools`, you should see the script `skexp` in your PATH. For a given nuclear charge $Z$ it will print the requested amount of exponents for your STOs. The number of exponents should be chosen so that the one-center calculations are converged. A too large number of exponents will lead to linear dependencies and the `slateratom` code halting.

Best regards
Tammo
